import { Order } from "./order-lists-types";

export const ordersData: Order[] = [
  {
    id: "4",
    date: "26-08-2025",
    tracking: "QRST789Z",
    client: "Fatima Zehra",
    contact: "0698765432",
    wilaya: "Annaba",
    address: "Sidi Amar",
    hub: "HubAnnaba",
    order: "Books set",
    totalPrice: "3200 dzd",
    delivery: "Standard",
    procedure: "COD",
    condition: "cancelled",
  },
  {
    id: "5",
    date: "25-08-2025",
    tracking: "UVWX012A",
    client: "Mohamed Cherif",
    contact: "0777888999",
    wilaya: "Alger",
    address: "Bab Ezzouar",
    hub: "HubAlger",
    order: "Headphones",
    totalPrice: "6700 dzd",
    delivery: "Stopdesk",
    procedure: "Change",
    condition: "delivered",
  },
  {
    id: "6",
    date: "24-08-2025",
    tracking: "EFGH345B",
    client: "Amina Khadija",
    contact: "0666555444",
    wilaya: "Setif",
    address: "El Eulma",
    hub: "HubSetif",
    order: "Clothing",
    totalPrice: "4100 dzd",
    delivery: "Express",
    procedure: "Prepaid",
    condition: "delivered",
  },
  {
    id: "7",
    date: "23-08-2025",
    tracking: "IJKL678C",
    client: "Youssef Rachid",
    contact: "0587321654",
    wilaya: "Oran",
    address: "Es Senia",
    hub: "HubOran",
    order: "Electronics",
    totalPrice: "8900 dzd",
    delivery: "Door to door",
    procedure: "COD",
    condition: "pending",
  },
  {
    id: "8",
    date: "22-08-2025",
    tracking: "NOPQ901D",
    client: "Leila Nassim",
    contact: "0612345678",
    wilaya: "Blida",
    address: "Chrea",
    hub: "HubBlida",
    order: "Home decor",
    totalPrice: "5500 dzd",
    delivery: "Standard",
    procedure: "Change",
    condition: "processing",
  },
];
