import { Vendor } from "./vendors-types";

export const vendorsData: Vendor[] = [
  {
    id: "VEN001",
    firstName: "Ahmed",
    lastName: "Hassan",
    phoneNumber: "+20 100 123 4567",
    emailAddress: "ahmed.hassan@email.com",
    storeName: "Ahmed's Electronics",
    hub: "Cairo Hub",
    status: "active",
  },
  {
    id: "VEN002",
    firstName: "Fatima",
    lastName: "Ali",
    phoneNumber: "+20 101 234 5678",
    emailAddress: "fatima.ali@email.com",
    storeName: "Fatima's Fashion",
    hub: "Alexandria Hub",
    status: "pending",
  },
  {
    id: "VEN003",
    firstName: "Mohammed",
    lastName: "Salah",
    phoneNumber: "+20 102 345 6789",
    emailAddress: "mohammed.salah@email.com",
    storeName: "Salah's Sports",
    hub: "Giza Hub",
    status: "inactive",
  },
  {
    id: "VEN004",
    firstName: "Nour",
    lastName: "Ibrahim",
    phoneNumber: "+20 103 456 7890",
    emailAddress: "nour.ibrahim@email.com",
    storeName: "Nour's Books",
    hub: "Cairo Hub",
    status: "active",
  },
  {
    id: "VEN005",
    firstName: "Omar",
    lastName: "Khaled",
    phoneNumber: "+20 104 567 8901",
    emailAddress: "omar.khaled@email.com",
    storeName: "Omar's Gadgets",
    hub: "Mansoura Hub",
    status: "pending",
  },
];
