import { Moderator } from "./moderators-types";

export const moderatorsData: Moderator[] = [
  {
    id: "#123",
    firstName: "Hamza",
    lastName: "Bouchanane",
    phoneNumber: "0549461543",
    emailAddress: "hamza@gmail.com",
    permissions: ["Edit Hubs", "Edit vendors", "Edit delivery men"],
    status: "active",
  },
  {
    id: "#124",
    firstName: "Amina",
    lastName: "Khelifi",
    phoneNumber: "0554123456",
    emailAddress: "amina.khelifi@gmail.com",
    permissions: ["Edit delivery men"],
    status: "blocked",
  },
  {
    id: "#125",
    firstName: "Mohamed",
    lastName: "Benali",
    phoneNumber: "0661234567",
    emailAddress: "mohamed.benali@gmail.com",
    permissions: ["Edit delivery men"],
    status: "active",
  },
  {
    id: "#126",
    firstName: "Fatima",
    lastName: "Ouali",
    phoneNumber: "0798765432",
    emailAddress: "fatima.ouali@gmail.com",
    permissions: ["Edit delivery men"],
    status: "active",
  },
  {
    id: "#127",
    firstName: "Youssef",
    lastName: "Naceri",
    phoneNumber: "0556789123",
    emailAddress: "youssef.naceri@gmail.com",
    permissions: ["Edit Hubs", "Edit vendors", "Edit delivery men"],
    status: "blocked",
  },
  {
    id: "#128",
    firstName: "Leila",
    lastName: "Hadj",
    phoneNumber: "0672345678",
    emailAddress: "leila.hadj@gmail.com",
    permissions: ["Edit Hubs", "Edit vendors", "Edit delivery men"],
    status: "blocked",
  },
  {
    id: "#129",
    firstName: "Karim",
    lastName: "Boudjema",
    phoneNumber: "0543876521",
    emailAddress: "karim.boudjema@gmail.com",
    permissions: ["Edit delivery men"],
    status: "active",
  },
];
