import { Transaction } from "./transactions-types";

export const transactionsData: Transaction[] = [
  {
    id: "#123",
    date: "10-10-2025",
    hour: "11:02",
    transactionType: "client-order-payment",
    amount: 12300,
    initiator: "Client – Samir Boudjelal",
    beneficiary: "Seller – Amina Khelifi",
    description: "Purchase of 3 items",
    status: "successful",
  },
  {
    id: "#124",
    date: "10-10-2025",
    hour: "11:15",
    transactionType: "platform-commission",
    amount: 1230,
    initiator: "Seller – Amina Khelifi",
    beneficiary: "Platform",
    description: "10% fee from order TX-M001",
    status: "successful",
  },
  {
    id: "#125",
    date: "10-10-2025",
    hour: "11:30",
    transactionType: "seller-payout",
    amount: 11070,
    initiator: "Platform",
    beneficiary: "Seller – Amina Khelifi",
    description: "Purchase of 3 items",
    status: "successful",
  },
  {
    id: "#126",
    date: "10-10-2025",
    hour: "12:00",
    transactionType: "hub-delivery-payment",
    amount: 500,
    initiator: "Platform",
    beneficiary: "Hub – Mourad Benyahia (Boumerdès)",
    description: "Payment for 5 successful deliveries",
    status: "failure",
  },
  {
    id: "#127",
    date: "10-10-2025",
    hour: "12:15",
    transactionType: "client-order-payment",
    amount: 8500,
    initiator: "Client – Samir Boudjelal",
    beneficiary: "Seller – Amina Khelifi",
    description: "Payment for 5 successful deliveries",
    status: "in-progress",
  },
  {
    id: "#128",
    date: "11-10-2025",
    hour: "09:30",
    transactionType: "hub-delivery-payment",
    amount: 750,
    initiator: "Platform",
    beneficiary: "Hub – Mourad Benyahia (Boumerdès)",
    description: "Payment for 5 successful deliveries",
    status: "failure",
  },
  {
    id: "#129",
    date: "11-10-2025",
    hour: "10:45",
    transactionType: "platform-commission",
    amount: 850,
    initiator: "Seller – Amina Khelifi",
    beneficiary: "Platform",
    description: "10% fee from order TX-M001",
    status: "successful",
  },
  {
    id: "#130",
    date: "11-10-2025",
    hour: "14:20",
    transactionType: "platform-commission",
    amount: 920,
    initiator: "Seller – Amina Khelifi",
    beneficiary: "Platform",
    description: "10% fee from order TX-M001",
    status: "successful",
  },
];
