import { DeliveryMan } from "./delivery-men-types";

export const deliveryMenData: DeliveryMan[] = [
  {
    id: "#123",
    firstName: "Hamza",
    lastName: "Bouchanane",
    phoneNumber: "0549461543",
    emailAddress: "hamza@gmail.com",
    dateOfBirth: "12-12-2001",
    status: "active",
  },
  {
    id: "#124",
    firstName: "Ahmed",
    lastName: "Benali",
    phoneNumber: "0558123456",
    emailAddress: "ahmed.benali@gmail.com",
    dateOfBirth: "05-07-1995",
    status: "active",
  },
  {
    id: "#125",
    firstName: "Mohamed",
    lastName: "Slimani",
    phoneNumber: "0567890123",
    emailAddress: "mohamed.slimani@gmail.com",
    dateOfBirth: "18-03-1988",
    status: "inactive",
  },
  {
    id: "#126",
    firstName: "Youssef",
    lastName: "Khoury",
    phoneNumber: "0576543210",
    emailAddress: "youssef.khoury@gmail.com",
    dateOfBirth: "22-11-1992",
    status: "active",
  },
  {
    id: "#127",
    firstName: "Karim",
    lastName: "Mansouri",
    phoneNumber: "0534567890",
    emailAddress: "karim.mansouri@gmail.com",
    dateOfBirth: "10-09-1987",
    status: "active",
  },
  {
    id: "#128",
    firstName: "Omar",
    lastName: "Cherif",
    phoneNumber: "0545678901",
    emailAddress: "omar.cherif@gmail.com",
    dateOfBirth: "03-02-1993",
    status: "inactive",
  },
  {
    id: "#129",
    firstName: "Ali",
    lastName: "Nasri",
    phoneNumber: "0556789012",
    emailAddress: "ali.nasri@gmail.com",
    dateOfBirth: "25-08-1990",
    status: "active",
  },
  {
    id: "#130",
    firstName: "Hassan",
    lastName: "Fares",
    phoneNumber: "0567890123",
    emailAddress: "hassan.fares@gmail.com",
    dateOfBirth: "14-06-1985",
    status: "active",
  },
];
